### ISSUE TITLE
is it possible to connect to wifi on windows raspberry pi?

### ISSUE THREAD

**Issue by Tiger3x** [worproject/RPi-Windows-Drivers#5] opened 2020-10-23 13:13 UTC
is it possible to connect to wifi on windows raspberry pi?

**Comment by worproject** [comment] 2020-10-23 14:32
Duplicate of: https://github.com/worproject/RPi-Windows-Drivers/issues/4
The answer is no.

**Closed as completed by worproject** 2020-10-23 14:32 UTC
