### ISSUE TITLE
Bluetooth Not working

### ISSUE THREAD

**Issue by Ddongddi** [worproject/RPi-Windows-Drivers#18] opened 2021-05-29 00:15 UTC
Hello.
Do you know why is Bluetooth driver not working?
I installed the driver and it's giving me Code 10 error

This is the error : 
`This device cannot start. (Code 10)

{Drive Not Ready}
The drive is not ready for use; its door may be open. Please check drive %hs and make sure that a disk is inserted and that the drive door is closed.`

**Comment by mariobalanica** [comment] 2021-07-03 17:11
Fixed in the latest driver package release.

**Closed as completed by mariobalanica** 2021-07-03 17:11 UTC

**Comment by SquallATF** [comment] 2021-07-04 14:17
I have updated SerPL011 and cywbtserialbus drivers to the latest version, but still get code 10 error?

**Comment by mariobalanica** [comment] 2021-07-04 15:10
Try re-installing the OS with the latest driver package. 
I cannot reproduce this issue on a Pi 4 running build 22000.1.
